export const SAVE_GST_RETURN = 'SAVE_GST_RETURN';
export const UPDATE_GST_RETURN = 'UPDATE_GST_RETURN';
export const UPDATE_GST_NEW = 'UPDATE_GST_RETURN';



export const UPDATE_SALES_AND_INCOME = 'UPDATE_SALES_AND_INCOME';
export const UPDATE_PURCHASE_AND_EXPENSE = 'UPDATE_PURCHASE_AND_EXPENSE';
export const UPDATE_DEBIT_ADJUSTMENTS = 'UPDATE_DEBIT_ADJUSTMENTS';
export const UPDATE_CREDIT_ADJUSTMENTS = 'UPDATE_CREDIT_ADJUSTMENTS';